Repository keymanapp/s.keyman.com, pull requests merged in 2023-10, with the labels that each got.

#84 Upate build.sh and add test 🦭
  .github/workflows/ci.yml
  Dockerfile
  build.sh
  resources/builder.inc.sh
Labels: staging

#105 chore: Generate static file in init-container.sh
  .gitattributes
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  build.sh
  deploy/jq-win64.exe
  deploy/jq.inc.sh
  deploy/kmwversion.sh
  resources/builder.inc.sh
  resources/init-container.sh
Labels: staging

#109 feat: auto merge keyman-server PRs
  .github/workflows/auto-approve-keyman-server-pr.yml
  .github/workflows/auto-merge-keyman-server-pr.yml
Labels: feat

#108 auto: Keyboard and font deployment
  keyboard/gff_tigre/1.0.2/gff_tigre-1.0.2.js
  keyboard/gff_tigrinya_eritrea/2.0.2/gff_tigrinya_eritrea-2.0.2.js
Labels: auto

#111 chore: auto merge cleanup
  .github/workflows/auto-approve-and-merge-keyman-server-pr.yml
  .github/workflows/auto-approve-keyman-server-pr.yml
  .github/workflows/auto-merge-keyman-server-pr.yml
Labels: feat

#112 auto: Keyboard and font deployment
  keyboard/gff_tigrinya_ethiopia/2.0.3/gff_tigrinya_ethiopia-2.0.3.js
Labels: auto

#113 auto: Keyboard and font deployment
  keyboard/fv_dene_zhatie/10.0.2/fv_dene_zhatie-10.0.2.js
  keyboard/fv_kwakwala_liqwala/9.2.5/fv_kwakwala_liqwala-9.2.5.js
Labels: auto

#114 auto: Keyboard and font deployment
  keyboard/malar_malayalam/1.7/malar_malayalam-1.7.js
Labels: auto

#115 auto: Keyboard and font deployment
  keyboard/newa_traditional_extended/1.0/newa_traditional_extended-1.0.js
Labels: auto

#116 auto: Keyboard and font deployment
  keyboard/burushaski_girminas/2.0.25/burushaski_girminas-2.0.25.js
Labels: auto

#117 chore: new auth for auto merge
  .github/workflows/auto-approve-and-merge-keyman-server-pr.yml
Labels: feat

#118 auto: Keyboard and font deployment
  keyboard/newa_traditional_extended/1.0.1/newa_traditional_extended-1.0.1.js
Labels: auto

#119 auto: Keyboard and font deployment
  keyboard/warang_citi/1.1.2/warang_citi-1.1.2.js
Labels: auto

#120 auto: KeymanWeb release 17.0.203
  kmw/engine/17.0.203/keymanweb.js
  kmw/engine/17.0.203/keymanweb.js.map
  kmw/engine/17.0.203/kmwuibutton.js
  kmw/engine/17.0.203/kmwuibutton.js.map
  kmw/engine/17.0.203/kmwuifloat.js
  kmw/engine/17.0.203/kmwuifloat.js.map
  kmw/engine/17.0.203/kmwuitoggle.js
  kmw/engine/17.0.203/kmwuitoggle.js.map
  kmw/engine/17.0.203/kmwuitoolbar.js
  kmw/engine/17.0.203/kmwuitoolbar.js.map
  kmw/engine/17.0.203/osk/ajax-loader.gif
  kmw/engine/17.0.203/osk/globe-hint.css
  kmw/engine/17.0.203/osk/keymanweb-osk.ttf
  kmw/engine/17.0.203/osk/kmwosk.css
  kmw/engine/17.0.203/ui/button/kbdicon.gif
  kmw/engine/17.0.203/ui/button/kmw_button.gif
  kmw/engine/17.0.203/ui/float/kbdicon.gif
  kmw/engine/17.0.203/ui/float/kmicon.gif
  kmw/engine/17.0.203/ui/ios/kbdicon.png
  kmw/engine/17.0.203/ui/toggle/kbdicon.gif
  kmw/engine/17.0.203/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.203/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.203/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.203/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.203/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.203/ui/toolbar/blank.gif
  kmw/engine/17.0.203/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.203/ui/toolbar/toolbar.gif
  kmw/engine/17.0.203/ui/toolbar/world.png
Labels: auto
