Repository keymanapp/s.keyman.com, pull requests merged in 2024-02, with the labels that each got.

#232 auto: KeymanWeb release 17.0.258
  kmw/engine/17.0.258/keymanweb.es5.js
  kmw/engine/17.0.258/keymanweb.es5.js.map
  kmw/engine/17.0.258/keymanweb.js
  kmw/engine/17.0.258/keymanweb.js.map
  kmw/engine/17.0.258/kmwuibutton.js
  kmw/engine/17.0.258/kmwuibutton.js.map
  kmw/engine/17.0.258/kmwuifloat.js
  kmw/engine/17.0.258/kmwuifloat.js.map
  kmw/engine/17.0.258/kmwuitoggle.js
  kmw/engine/17.0.258/kmwuitoggle.js.map
  kmw/engine/17.0.258/kmwuitoolbar.js
  kmw/engine/17.0.258/kmwuitoolbar.js.map
  kmw/engine/17.0.258/osk/ajax-loader.gif
  kmw/engine/17.0.258/osk/globe-hint.css
  kmw/engine/17.0.258/osk/keymanweb-osk.ttf
  kmw/engine/17.0.258/osk/kmwosk.css
  kmw/engine/17.0.258/ui/button/kbdicon.gif
  kmw/engine/17.0.258/ui/button/kmw_button.gif
  kmw/engine/17.0.258/ui/float/kbdicon.gif
  kmw/engine/17.0.258/ui/float/kmicon.gif
  kmw/engine/17.0.258/ui/ios/kbdicon.png
  kmw/engine/17.0.258/ui/toggle/kbdicon.gif
  kmw/engine/17.0.258/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.258/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.258/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.258/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.258/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.258/ui/toolbar/blank.gif
  kmw/engine/17.0.258/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.258/ui/toolbar/toolbar.gif
  kmw/engine/17.0.258/ui/toolbar/world.png
Labels: auto

#233 auto: Keyboard and font deployment
  keyboard/eo_plus/3.0.1/eo_plus-3.0.1.js
Labels: auto

#234 auto: KeymanWeb release 17.0.259
  kmw/engine/17.0.259/keymanweb.es5.js
  kmw/engine/17.0.259/keymanweb.es5.js.map
  kmw/engine/17.0.259/keymanweb.js
  kmw/engine/17.0.259/keymanweb.js.map
  kmw/engine/17.0.259/kmwuibutton.js
  kmw/engine/17.0.259/kmwuibutton.js.map
  kmw/engine/17.0.259/kmwuifloat.js
  kmw/engine/17.0.259/kmwuifloat.js.map
  kmw/engine/17.0.259/kmwuitoggle.js
  kmw/engine/17.0.259/kmwuitoggle.js.map
  kmw/engine/17.0.259/kmwuitoolbar.js
  kmw/engine/17.0.259/kmwuitoolbar.js.map
  kmw/engine/17.0.259/osk/ajax-loader.gif
  kmw/engine/17.0.259/osk/globe-hint.css
  kmw/engine/17.0.259/osk/keymanweb-osk.ttf
  kmw/engine/17.0.259/osk/kmwosk.css
  kmw/engine/17.0.259/ui/button/kbdicon.gif
  kmw/engine/17.0.259/ui/button/kmw_button.gif
  kmw/engine/17.0.259/ui/float/kbdicon.gif
  kmw/engine/17.0.259/ui/float/kmicon.gif
  kmw/engine/17.0.259/ui/ios/kbdicon.png
  kmw/engine/17.0.259/ui/toggle/kbdicon.gif
  kmw/engine/17.0.259/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.259/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.259/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.259/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.259/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.259/ui/toolbar/blank.gif
  kmw/engine/17.0.259/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.259/ui/toolbar/toolbar.gif
  kmw/engine/17.0.259/ui/toolbar/world.png
Labels: auto

#235 auto: KeymanWeb release 17.0.260
  kmw/engine/17.0.260/keymanweb.es5.js
  kmw/engine/17.0.260/keymanweb.es5.js.map
  kmw/engine/17.0.260/keymanweb.js
  kmw/engine/17.0.260/keymanweb.js.map
  kmw/engine/17.0.260/kmwuibutton.js
  kmw/engine/17.0.260/kmwuibutton.js.map
  kmw/engine/17.0.260/kmwuifloat.js
  kmw/engine/17.0.260/kmwuifloat.js.map
  kmw/engine/17.0.260/kmwuitoggle.js
  kmw/engine/17.0.260/kmwuitoggle.js.map
  kmw/engine/17.0.260/kmwuitoolbar.js
  kmw/engine/17.0.260/kmwuitoolbar.js.map
  kmw/engine/17.0.260/osk/ajax-loader.gif
  kmw/engine/17.0.260/osk/globe-hint.css
  kmw/engine/17.0.260/osk/keymanweb-osk.ttf
  kmw/engine/17.0.260/osk/kmwosk.css
  kmw/engine/17.0.260/ui/button/kbdicon.gif
  kmw/engine/17.0.260/ui/button/kmw_button.gif
  kmw/engine/17.0.260/ui/float/kbdicon.gif
  kmw/engine/17.0.260/ui/float/kmicon.gif
  kmw/engine/17.0.260/ui/ios/kbdicon.png
  kmw/engine/17.0.260/ui/toggle/kbdicon.gif
  kmw/engine/17.0.260/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.260/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.260/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.260/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.260/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.260/ui/toolbar/blank.gif
  kmw/engine/17.0.260/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.260/ui/toolbar/toolbar.gif
  kmw/engine/17.0.260/ui/toolbar/world.png
Labels: auto

#236 Update staging to use shared-sites v0.4
  build.sh
Labels: staging

#238 auto: Keyboard and font deployment
  keyboard/fv_hailzaqvla/9.5/fv_hailzaqvla-9.5.js
Labels: auto

#239 auto: KeymanWeb release 17.0.261
  kmw/engine/17.0.261/keymanweb.es5.js
  kmw/engine/17.0.261/keymanweb.es5.js.map
  kmw/engine/17.0.261/keymanweb.js
  kmw/engine/17.0.261/keymanweb.js.map
  kmw/engine/17.0.261/kmwuibutton.js
  kmw/engine/17.0.261/kmwuibutton.js.map
  kmw/engine/17.0.261/kmwuifloat.js
  kmw/engine/17.0.261/kmwuifloat.js.map
  kmw/engine/17.0.261/kmwuitoggle.js
  kmw/engine/17.0.261/kmwuitoggle.js.map
  kmw/engine/17.0.261/kmwuitoolbar.js
  kmw/engine/17.0.261/kmwuitoolbar.js.map
  kmw/engine/17.0.261/osk/ajax-loader.gif
  kmw/engine/17.0.261/osk/globe-hint.css
  kmw/engine/17.0.261/osk/keymanweb-osk.ttf
  kmw/engine/17.0.261/osk/kmwosk.css
  kmw/engine/17.0.261/ui/button/kbdicon.gif
  kmw/engine/17.0.261/ui/button/kmw_button.gif
  kmw/engine/17.0.261/ui/float/kbdicon.gif
  kmw/engine/17.0.261/ui/float/kmicon.gif
  kmw/engine/17.0.261/ui/ios/kbdicon.png
  kmw/engine/17.0.261/ui/toggle/kbdicon.gif
  kmw/engine/17.0.261/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.261/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.261/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.261/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.261/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.261/ui/toolbar/blank.gif
  kmw/engine/17.0.261/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.261/ui/toolbar/toolbar.gif
  kmw/engine/17.0.261/ui/toolbar/world.png
Labels: auto

#240 auto: KeymanWeb release 17.0.262
  kmw/engine/17.0.262/keymanweb.es5.js
  kmw/engine/17.0.262/keymanweb.es5.js.map
  kmw/engine/17.0.262/keymanweb.js
  kmw/engine/17.0.262/keymanweb.js.map
  kmw/engine/17.0.262/kmwuibutton.js
  kmw/engine/17.0.262/kmwuibutton.js.map
  kmw/engine/17.0.262/kmwuifloat.js
  kmw/engine/17.0.262/kmwuifloat.js.map
  kmw/engine/17.0.262/kmwuitoggle.js
  kmw/engine/17.0.262/kmwuitoggle.js.map
  kmw/engine/17.0.262/kmwuitoolbar.js
  kmw/engine/17.0.262/kmwuitoolbar.js.map
  kmw/engine/17.0.262/osk/ajax-loader.gif
  kmw/engine/17.0.262/osk/globe-hint.css
  kmw/engine/17.0.262/osk/keymanweb-osk.ttf
  kmw/engine/17.0.262/osk/kmwosk.css
  kmw/engine/17.0.262/ui/button/kbdicon.gif
  kmw/engine/17.0.262/ui/button/kmw_button.gif
  kmw/engine/17.0.262/ui/float/kbdicon.gif
  kmw/engine/17.0.262/ui/float/kmicon.gif
  kmw/engine/17.0.262/ui/ios/kbdicon.png
  kmw/engine/17.0.262/ui/toggle/kbdicon.gif
  kmw/engine/17.0.262/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.262/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.262/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.262/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.262/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.262/ui/toolbar/blank.gif
  kmw/engine/17.0.262/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.262/ui/toolbar/toolbar.gif
  kmw/engine/17.0.262/ui/toolbar/world.png
Labels: auto

#241 auto: Keyboard and font deployment
  keyboard/fv_nsilxcen/9.3/fv_nsilxcen-9.3.js
Labels: auto

#242 auto: Keyboard and font deployment
  keyboard/fv_denesuline/10.0.1/fv_denesuline-10.0.1.js
  keyboard/fv_denesuline_epsilon/10.0.1/fv_denesuline_epsilon-10.0.1.js
Labels: auto

#244 chore: Add liveliness check
  _control/alive.txt
Labels: chore, staging

#245 auto: KeymanWeb release 17.0.263
  kmw/engine/17.0.263/keymanweb.es5.js
  kmw/engine/17.0.263/keymanweb.es5.js.map
  kmw/engine/17.0.263/keymanweb.js
  kmw/engine/17.0.263/keymanweb.js.map
  kmw/engine/17.0.263/kmwuibutton.js
  kmw/engine/17.0.263/kmwuibutton.js.map
  kmw/engine/17.0.263/kmwuifloat.js
  kmw/engine/17.0.263/kmwuifloat.js.map
  kmw/engine/17.0.263/kmwuitoggle.js
  kmw/engine/17.0.263/kmwuitoggle.js.map
  kmw/engine/17.0.263/kmwuitoolbar.js
  kmw/engine/17.0.263/kmwuitoolbar.js.map
  kmw/engine/17.0.263/osk/ajax-loader.gif
  kmw/engine/17.0.263/osk/globe-hint.css
  kmw/engine/17.0.263/osk/keymanweb-osk.ttf
  kmw/engine/17.0.263/osk/kmwosk.css
  kmw/engine/17.0.263/ui/button/kbdicon.gif
  kmw/engine/17.0.263/ui/button/kmw_button.gif
  kmw/engine/17.0.263/ui/float/kbdicon.gif
  kmw/engine/17.0.263/ui/float/kmicon.gif
  kmw/engine/17.0.263/ui/ios/kbdicon.png
  kmw/engine/17.0.263/ui/toggle/kbdicon.gif
  kmw/engine/17.0.263/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.263/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.263/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.263/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.263/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.263/ui/toolbar/blank.gif
  kmw/engine/17.0.263/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.263/ui/toolbar/toolbar.gif
  kmw/engine/17.0.263/ui/toolbar/world.png
Labels: auto

#248 auto: Keyboard and font deployment
  keyboard/fv_cree_latin/10.0/fv_cree_latin-10.0.js
Labels: auto

#243 chore: b17s1 merge staging into master
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .gitignore
  .htaccess
  App_Data/jobs/continuous/deploy/README.md
  App_Data/jobs/continuous/deploy/run.bat
  App_Data/jobs/continuous/deploy/settings.job
  Dockerfile
  _control/alive
  _control/info.php
  _control/ready.php
  api/deploy.php
  api/webhooks.php
  build.sh
  deploy/jq-win64.exe
  deploy/jq.inc.sh
  deploy/kmwversion.sh
  kmw/engine/.htaccess
  kmw/engine/web.config
  resources/init-container.sh
  web.config
Labels: chore

#252 auto: KeymanWeb release 17.0.265
  kmw/engine/17.0.265/keymanweb.es5.js
  kmw/engine/17.0.265/keymanweb.es5.js.map
  kmw/engine/17.0.265/keymanweb.js
  kmw/engine/17.0.265/keymanweb.js.map
  kmw/engine/17.0.265/kmwuibutton.js
  kmw/engine/17.0.265/kmwuibutton.js.map
  kmw/engine/17.0.265/kmwuifloat.js
  kmw/engine/17.0.265/kmwuifloat.js.map
  kmw/engine/17.0.265/kmwuitoggle.js
  kmw/engine/17.0.265/kmwuitoggle.js.map
  kmw/engine/17.0.265/kmwuitoolbar.js
  kmw/engine/17.0.265/kmwuitoolbar.js.map
  kmw/engine/17.0.265/osk/ajax-loader.gif
  kmw/engine/17.0.265/osk/globe-hint.css
  kmw/engine/17.0.265/osk/keymanweb-osk.ttf
  kmw/engine/17.0.265/osk/kmwosk.css
  kmw/engine/17.0.265/ui/button/kbdicon.gif
  kmw/engine/17.0.265/ui/button/kmw_button.gif
  kmw/engine/17.0.265/ui/float/kbdicon.gif
  kmw/engine/17.0.265/ui/float/kmicon.gif
  kmw/engine/17.0.265/ui/ios/kbdicon.png
  kmw/engine/17.0.265/ui/toggle/kbdicon.gif
  kmw/engine/17.0.265/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.265/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.265/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.265/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.265/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.265/ui/toolbar/blank.gif
  kmw/engine/17.0.265/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.265/ui/toolbar/toolbar.gif
  kmw/engine/17.0.265/ui/toolbar/world.png
Labels: auto

#254 auto: KeymanWeb release 17.0.266
  kmw/engine/17.0.266/keymanweb.es5.js
  kmw/engine/17.0.266/keymanweb.es5.js.map
  kmw/engine/17.0.266/keymanweb.js
  kmw/engine/17.0.266/keymanweb.js.map
  kmw/engine/17.0.266/kmwuibutton.js
  kmw/engine/17.0.266/kmwuibutton.js.map
  kmw/engine/17.0.266/kmwuifloat.js
  kmw/engine/17.0.266/kmwuifloat.js.map
  kmw/engine/17.0.266/kmwuitoggle.js
  kmw/engine/17.0.266/kmwuitoggle.js.map
  kmw/engine/17.0.266/kmwuitoolbar.js
  kmw/engine/17.0.266/kmwuitoolbar.js.map
  kmw/engine/17.0.266/osk/ajax-loader.gif
  kmw/engine/17.0.266/osk/globe-hint.css
  kmw/engine/17.0.266/osk/keymanweb-osk.ttf
  kmw/engine/17.0.266/osk/kmwosk.css
  kmw/engine/17.0.266/ui/button/kbdicon.gif
  kmw/engine/17.0.266/ui/button/kmw_button.gif
  kmw/engine/17.0.266/ui/float/kbdicon.gif
  kmw/engine/17.0.266/ui/float/kmicon.gif
  kmw/engine/17.0.266/ui/ios/kbdicon.png
  kmw/engine/17.0.266/ui/toggle/kbdicon.gif
  kmw/engine/17.0.266/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.266/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.266/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.266/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.266/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.266/ui/toolbar/blank.gif
  kmw/engine/17.0.266/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.266/ui/toolbar/toolbar.gif
  kmw/engine/17.0.266/ui/toolbar/world.png
Labels: auto

#255 auto: Keyboard and font deployment
  keyboard/hcesar/1.1.1/hcesar-1.1.1.js
Labels: auto

#256 auto: Keyboard and font deployment
  keyboard/ife_mn/1.0/ife_mn-1.0.js
Labels: auto

#253 chore: Add info to .htaccess
  .htaccess
  _control/info.php
Labels: production

#257 auto: Keyboard and font deployment
  keyboard/fv_gitsenimx/10.0.1/fv_gitsenimx-10.0.1.js
Labels: auto

#258 auto: Keyboard and font deployment
  keyboard/itrans_roman/1.2.0/itrans_roman-1.2.0.js
Labels: auto

#259 auto: KeymanWeb release 17.0.267
  kmw/engine/17.0.267/keymanweb.es5.js
  kmw/engine/17.0.267/keymanweb.es5.js.map
  kmw/engine/17.0.267/keymanweb.js
  kmw/engine/17.0.267/keymanweb.js.map
  kmw/engine/17.0.267/kmwuibutton.js
  kmw/engine/17.0.267/kmwuibutton.js.map
  kmw/engine/17.0.267/kmwuifloat.js
  kmw/engine/17.0.267/kmwuifloat.js.map
  kmw/engine/17.0.267/kmwuitoggle.js
  kmw/engine/17.0.267/kmwuitoggle.js.map
  kmw/engine/17.0.267/kmwuitoolbar.js
  kmw/engine/17.0.267/kmwuitoolbar.js.map
  kmw/engine/17.0.267/osk/ajax-loader.gif
  kmw/engine/17.0.267/osk/globe-hint.css
  kmw/engine/17.0.267/osk/keymanweb-osk.ttf
  kmw/engine/17.0.267/osk/kmwosk.css
  kmw/engine/17.0.267/ui/button/kbdicon.gif
  kmw/engine/17.0.267/ui/button/kmw_button.gif
  kmw/engine/17.0.267/ui/float/kbdicon.gif
  kmw/engine/17.0.267/ui/float/kmicon.gif
  kmw/engine/17.0.267/ui/ios/kbdicon.png
  kmw/engine/17.0.267/ui/toggle/kbdicon.gif
  kmw/engine/17.0.267/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.267/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.267/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.267/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.267/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.267/ui/toolbar/blank.gif
  kmw/engine/17.0.267/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.267/ui/toolbar/toolbar.gif
  kmw/engine/17.0.267/ui/toolbar/world.png
Labels: auto

#261 auto: KeymanWeb release 17.0.268
  kmw/engine/17.0.268/keymanweb.es5.js
  kmw/engine/17.0.268/keymanweb.es5.js.map
  kmw/engine/17.0.268/keymanweb.js
  kmw/engine/17.0.268/keymanweb.js.map
  kmw/engine/17.0.268/kmwuibutton.js
  kmw/engine/17.0.268/kmwuibutton.js.map
  kmw/engine/17.0.268/kmwuifloat.js
  kmw/engine/17.0.268/kmwuifloat.js.map
  kmw/engine/17.0.268/kmwuitoggle.js
  kmw/engine/17.0.268/kmwuitoggle.js.map
  kmw/engine/17.0.268/kmwuitoolbar.js
  kmw/engine/17.0.268/kmwuitoolbar.js.map
  kmw/engine/17.0.268/osk/ajax-loader.gif
  kmw/engine/17.0.268/osk/globe-hint.css
  kmw/engine/17.0.268/osk/keymanweb-osk.ttf
  kmw/engine/17.0.268/osk/kmwosk.css
  kmw/engine/17.0.268/ui/button/kbdicon.gif
  kmw/engine/17.0.268/ui/button/kmw_button.gif
  kmw/engine/17.0.268/ui/float/kbdicon.gif
  kmw/engine/17.0.268/ui/float/kmicon.gif
  kmw/engine/17.0.268/ui/ios/kbdicon.png
  kmw/engine/17.0.268/ui/toggle/kbdicon.gif
  kmw/engine/17.0.268/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.268/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.268/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.268/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.268/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.268/ui/toolbar/blank.gif
  kmw/engine/17.0.268/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.268/ui/toolbar/toolbar.gif
  kmw/engine/17.0.268/ui/toolbar/world.png
Labels: auto

#262 auto: KeymanWeb release 17.0.268
  kmw/engine/18.0.1/keymanweb.es5.js
  kmw/engine/18.0.1/keymanweb.es5.js.map
  kmw/engine/18.0.1/keymanweb.js
  kmw/engine/18.0.1/keymanweb.js.map
  kmw/engine/18.0.1/kmwuibutton.js
  kmw/engine/18.0.1/kmwuibutton.js.map
  kmw/engine/18.0.1/kmwuifloat.js
  kmw/engine/18.0.1/kmwuifloat.js.map
  kmw/engine/18.0.1/kmwuitoggle.js
  kmw/engine/18.0.1/kmwuitoggle.js.map
  kmw/engine/18.0.1/kmwuitoolbar.js
  kmw/engine/18.0.1/kmwuitoolbar.js.map
  kmw/engine/18.0.1/osk/ajax-loader.gif
  kmw/engine/18.0.1/osk/globe-hint.css
  kmw/engine/18.0.1/osk/keymanweb-osk.ttf
  kmw/engine/18.0.1/osk/kmwosk.css
  kmw/engine/18.0.1/ui/button/kbdicon.gif
  kmw/engine/18.0.1/ui/button/kmw_button.gif
  kmw/engine/18.0.1/ui/float/kbdicon.gif
  kmw/engine/18.0.1/ui/float/kmicon.gif
  kmw/engine/18.0.1/ui/ios/kbdicon.png
  kmw/engine/18.0.1/ui/toggle/kbdicon.gif
  kmw/engine/18.0.1/ui/toggle/kmw_logo_16.gif
  kmw/engine/18.0.1/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/18.0.1/ui/toggle/kmw_osk_16.gif
  kmw/engine/18.0.1/ui/toggle/kmwcontroller2.gif
  kmw/engine/18.0.1/ui/toggle/kmwcontroller2x.gif
  kmw/engine/18.0.1/ui/toolbar/blank.gif
  kmw/engine/18.0.1/ui/toolbar/kmwuitoolbar.css
  kmw/engine/18.0.1/ui/toolbar/toolbar.gif
  kmw/engine/18.0.1/ui/toolbar/world.png
Labels: auto

#263 auto: KeymanWeb release 18.0.1
  kmw/engine/17.0.269/keymanweb.es5.js
  kmw/engine/17.0.269/keymanweb.es5.js.map
  kmw/engine/17.0.269/keymanweb.js
  kmw/engine/17.0.269/keymanweb.js.map
  kmw/engine/17.0.269/kmwuibutton.js
  kmw/engine/17.0.269/kmwuibutton.js.map
  kmw/engine/17.0.269/kmwuifloat.js
  kmw/engine/17.0.269/kmwuifloat.js.map
  kmw/engine/17.0.269/kmwuitoggle.js
  kmw/engine/17.0.269/kmwuitoggle.js.map
  kmw/engine/17.0.269/kmwuitoolbar.js
  kmw/engine/17.0.269/kmwuitoolbar.js.map
  kmw/engine/17.0.269/osk/ajax-loader.gif
  kmw/engine/17.0.269/osk/globe-hint.css
  kmw/engine/17.0.269/osk/keymanweb-osk.ttf
  kmw/engine/17.0.269/osk/kmwosk.css
  kmw/engine/17.0.269/ui/button/kbdicon.gif
  kmw/engine/17.0.269/ui/button/kmw_button.gif
  kmw/engine/17.0.269/ui/float/kbdicon.gif
  kmw/engine/17.0.269/ui/float/kmicon.gif
  kmw/engine/17.0.269/ui/ios/kbdicon.png
  kmw/engine/17.0.269/ui/toggle/kbdicon.gif
  kmw/engine/17.0.269/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.269/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.269/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.269/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.269/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.269/ui/toolbar/blank.gif
  kmw/engine/17.0.269/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.269/ui/toolbar/toolbar.gif
  kmw/engine/17.0.269/ui/toolbar/world.png
Labels: auto

#264 auto: Keyboard and font deployment
  keyboard/yo/1.0.2/yo-1.0.2.js
Labels: auto

#265 auto: Keyboard and font deployment
  keyboard/fv_hlgaagilda_xaayda_kil/9.3/fv_hlgaagilda_xaayda_kil-9.3.js
Labels: auto

#266 auto: Keyboard and font deployment
  keyboard/itrans_bengali/1.0.2/itrans_bengali-1.0.2.js
Labels: auto

#267 auto: KeymanWeb release 17.0.270
  kmw/engine/17.0.270/keymanweb.es5.js
  kmw/engine/17.0.270/keymanweb.es5.js.map
  kmw/engine/17.0.270/keymanweb.js
  kmw/engine/17.0.270/keymanweb.js.map
  kmw/engine/17.0.270/kmwuibutton.js
  kmw/engine/17.0.270/kmwuibutton.js.map
  kmw/engine/17.0.270/kmwuifloat.js
  kmw/engine/17.0.270/kmwuifloat.js.map
  kmw/engine/17.0.270/kmwuitoggle.js
  kmw/engine/17.0.270/kmwuitoggle.js.map
  kmw/engine/17.0.270/kmwuitoolbar.js
  kmw/engine/17.0.270/kmwuitoolbar.js.map
  kmw/engine/17.0.270/osk/ajax-loader.gif
  kmw/engine/17.0.270/osk/globe-hint.css
  kmw/engine/17.0.270/osk/keymanweb-osk.ttf
  kmw/engine/17.0.270/osk/kmwosk.css
  kmw/engine/17.0.270/ui/button/kbdicon.gif
  kmw/engine/17.0.270/ui/button/kmw_button.gif
  kmw/engine/17.0.270/ui/float/kbdicon.gif
  kmw/engine/17.0.270/ui/float/kmicon.gif
  kmw/engine/17.0.270/ui/ios/kbdicon.png
  kmw/engine/17.0.270/ui/toggle/kbdicon.gif
  kmw/engine/17.0.270/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.270/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.270/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.270/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.270/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.270/ui/toolbar/blank.gif
  kmw/engine/17.0.270/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.270/ui/toolbar/toolbar.gif
  kmw/engine/17.0.270/ui/toolbar/world.png
Labels: auto

#268 auto: KeymanWeb release 17.0.271
  kmw/engine/17.0.271/keymanweb.es5.js
  kmw/engine/17.0.271/keymanweb.es5.js.map
  kmw/engine/17.0.271/keymanweb.js
  kmw/engine/17.0.271/keymanweb.js.map
  kmw/engine/17.0.271/kmwuibutton.js
  kmw/engine/17.0.271/kmwuibutton.js.map
  kmw/engine/17.0.271/kmwuifloat.js
  kmw/engine/17.0.271/kmwuifloat.js.map
  kmw/engine/17.0.271/kmwuitoggle.js
  kmw/engine/17.0.271/kmwuitoggle.js.map
  kmw/engine/17.0.271/kmwuitoolbar.js
  kmw/engine/17.0.271/kmwuitoolbar.js.map
  kmw/engine/17.0.271/osk/ajax-loader.gif
  kmw/engine/17.0.271/osk/globe-hint.css
  kmw/engine/17.0.271/osk/keymanweb-osk.ttf
  kmw/engine/17.0.271/osk/kmwosk.css
  kmw/engine/17.0.271/ui/button/kbdicon.gif
  kmw/engine/17.0.271/ui/button/kmw_button.gif
  kmw/engine/17.0.271/ui/float/kbdicon.gif
  kmw/engine/17.0.271/ui/float/kmicon.gif
  kmw/engine/17.0.271/ui/ios/kbdicon.png
  kmw/engine/17.0.271/ui/toggle/kbdicon.gif
  kmw/engine/17.0.271/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.271/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.271/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.271/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.271/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.271/ui/toolbar/blank.gif
  kmw/engine/17.0.271/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.271/ui/toolbar/toolbar.gif
  kmw/engine/17.0.271/ui/toolbar/world.png
Labels: auto

#270 auto: KeymanWeb release 17.0.272
  kmw/engine/17.0.272/keymanweb.es5.js
  kmw/engine/17.0.272/keymanweb.es5.js.map
  kmw/engine/17.0.272/keymanweb.js
  kmw/engine/17.0.272/keymanweb.js.map
  kmw/engine/17.0.272/kmwuibutton.js
  kmw/engine/17.0.272/kmwuibutton.js.map
  kmw/engine/17.0.272/kmwuifloat.js
  kmw/engine/17.0.272/kmwuifloat.js.map
  kmw/engine/17.0.272/kmwuitoggle.js
  kmw/engine/17.0.272/kmwuitoggle.js.map
  kmw/engine/17.0.272/kmwuitoolbar.js
  kmw/engine/17.0.272/kmwuitoolbar.js.map
  kmw/engine/17.0.272/osk/ajax-loader.gif
  kmw/engine/17.0.272/osk/globe-hint.css
  kmw/engine/17.0.272/osk/keymanweb-osk.ttf
  kmw/engine/17.0.272/osk/kmwosk.css
  kmw/engine/17.0.272/ui/button/kbdicon.gif
  kmw/engine/17.0.272/ui/button/kmw_button.gif
  kmw/engine/17.0.272/ui/float/kbdicon.gif
  kmw/engine/17.0.272/ui/float/kmicon.gif
  kmw/engine/17.0.272/ui/ios/kbdicon.png
  kmw/engine/17.0.272/ui/toggle/kbdicon.gif
  kmw/engine/17.0.272/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.272/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.272/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.272/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.272/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.272/ui/toolbar/blank.gif
  kmw/engine/17.0.272/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.272/ui/toolbar/toolbar.gif
  kmw/engine/17.0.272/ui/toolbar/world.png
Labels: auto

#271 auto: KeymanWeb release 18.0.3
  kmw/engine/18.0.3/keymanweb.es5.js
  kmw/engine/18.0.3/keymanweb.es5.js.map
  kmw/engine/18.0.3/keymanweb.js
  kmw/engine/18.0.3/keymanweb.js.map
  kmw/engine/18.0.3/kmwuibutton.js
  kmw/engine/18.0.3/kmwuibutton.js.map
  kmw/engine/18.0.3/kmwuifloat.js
  kmw/engine/18.0.3/kmwuifloat.js.map
  kmw/engine/18.0.3/kmwuitoggle.js
  kmw/engine/18.0.3/kmwuitoggle.js.map
  kmw/engine/18.0.3/kmwuitoolbar.js
  kmw/engine/18.0.3/kmwuitoolbar.js.map
  kmw/engine/18.0.3/osk/ajax-loader.gif
  kmw/engine/18.0.3/osk/globe-hint.css
  kmw/engine/18.0.3/osk/keymanweb-osk.ttf
  kmw/engine/18.0.3/osk/kmwosk.css
  kmw/engine/18.0.3/ui/button/kbdicon.gif
  kmw/engine/18.0.3/ui/button/kmw_button.gif
  kmw/engine/18.0.3/ui/float/kbdicon.gif
  kmw/engine/18.0.3/ui/float/kmicon.gif
  kmw/engine/18.0.3/ui/ios/kbdicon.png
  kmw/engine/18.0.3/ui/toggle/kbdicon.gif
  kmw/engine/18.0.3/ui/toggle/kmw_logo_16.gif
  kmw/engine/18.0.3/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/18.0.3/ui/toggle/kmw_osk_16.gif
  kmw/engine/18.0.3/ui/toggle/kmwcontroller2.gif
  kmw/engine/18.0.3/ui/toggle/kmwcontroller2x.gif
  kmw/engine/18.0.3/ui/toolbar/blank.gif
  kmw/engine/18.0.3/ui/toolbar/kmwuitoolbar.css
  kmw/engine/18.0.3/ui/toolbar/toolbar.gif
  kmw/engine/18.0.3/ui/toolbar/world.png
Labels: auto

#272 auto: KeymanWeb release 18.0.3
  kmw/engine/17.0.273/keymanweb.es5.js
  kmw/engine/17.0.273/keymanweb.es5.js.map
  kmw/engine/17.0.273/keymanweb.js
  kmw/engine/17.0.273/keymanweb.js.map
  kmw/engine/17.0.273/kmwuibutton.js
  kmw/engine/17.0.273/kmwuibutton.js.map
  kmw/engine/17.0.273/kmwuifloat.js
  kmw/engine/17.0.273/kmwuifloat.js.map
  kmw/engine/17.0.273/kmwuitoggle.js
  kmw/engine/17.0.273/kmwuitoggle.js.map
  kmw/engine/17.0.273/kmwuitoolbar.js
  kmw/engine/17.0.273/kmwuitoolbar.js.map
  kmw/engine/17.0.273/osk/ajax-loader.gif
  kmw/engine/17.0.273/osk/globe-hint.css
  kmw/engine/17.0.273/osk/keymanweb-osk.ttf
  kmw/engine/17.0.273/osk/kmwosk.css
  kmw/engine/17.0.273/ui/button/kbdicon.gif
  kmw/engine/17.0.273/ui/button/kmw_button.gif
  kmw/engine/17.0.273/ui/float/kbdicon.gif
  kmw/engine/17.0.273/ui/float/kmicon.gif
  kmw/engine/17.0.273/ui/ios/kbdicon.png
  kmw/engine/17.0.273/ui/toggle/kbdicon.gif
  kmw/engine/17.0.273/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.273/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.273/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.273/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.273/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.273/ui/toolbar/blank.gif
  kmw/engine/17.0.273/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.273/ui/toolbar/toolbar.gif
  kmw/engine/17.0.273/ui/toolbar/world.png
Labels: auto

#273 auto: Keyboard and font deployment
  keyboard/shebek/0.9.2/shebek-0.9.2.js
Labels: auto

#274 auto: Keyboard and font deployment
  keyboard/kashmiri_phonetic/1.0/kashmiri_phonetic-1.0.js
Labels: auto

#275 auto: Keyboard and font deployment
  keyboard/kashmiri_phonetic/1.0.1/kashmiri_phonetic-1.0.1.js
Labels: auto

#276 auto: Keyboard and font deployment
  keyboard/bj_cree_east/9.2.0/bj_cree_east-9.2.0.js
  keyboard/bj_oji_cree/9.2.0/bj_oji_cree-9.2.0.js
Labels: auto

#277 auto: KeymanWeb release 17.0.274
  kmw/engine/17.0.274/keymanweb.es5.js
  kmw/engine/17.0.274/keymanweb.es5.js.map
  kmw/engine/17.0.274/keymanweb.js
  kmw/engine/17.0.274/keymanweb.js.map
  kmw/engine/17.0.274/kmwuibutton.js
  kmw/engine/17.0.274/kmwuibutton.js.map
  kmw/engine/17.0.274/kmwuifloat.js
  kmw/engine/17.0.274/kmwuifloat.js.map
  kmw/engine/17.0.274/kmwuitoggle.js
  kmw/engine/17.0.274/kmwuitoggle.js.map
  kmw/engine/17.0.274/kmwuitoolbar.js
  kmw/engine/17.0.274/kmwuitoolbar.js.map
  kmw/engine/17.0.274/osk/ajax-loader.gif
  kmw/engine/17.0.274/osk/globe-hint.css
  kmw/engine/17.0.274/osk/keymanweb-osk.ttf
  kmw/engine/17.0.274/osk/kmwosk.css
  kmw/engine/17.0.274/ui/button/kbdicon.gif
  kmw/engine/17.0.274/ui/button/kmw_button.gif
  kmw/engine/17.0.274/ui/float/kbdicon.gif
  kmw/engine/17.0.274/ui/float/kmicon.gif
  kmw/engine/17.0.274/ui/ios/kbdicon.png
  kmw/engine/17.0.274/ui/toggle/kbdicon.gif
  kmw/engine/17.0.274/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.274/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.274/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.274/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.274/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.274/ui/toolbar/blank.gif
  kmw/engine/17.0.274/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.274/ui/toolbar/toolbar.gif
  kmw/engine/17.0.274/ui/toolbar/world.png
Labels: auto

#278 auto: KeymanWeb release 18.0.4
  kmw/engine/18.0.4/keymanweb.es5.js
  kmw/engine/18.0.4/keymanweb.es5.js.map
  kmw/engine/18.0.4/keymanweb.js
  kmw/engine/18.0.4/keymanweb.js.map
  kmw/engine/18.0.4/kmwuibutton.js
  kmw/engine/18.0.4/kmwuibutton.js.map
  kmw/engine/18.0.4/kmwuifloat.js
  kmw/engine/18.0.4/kmwuifloat.js.map
  kmw/engine/18.0.4/kmwuitoggle.js
  kmw/engine/18.0.4/kmwuitoggle.js.map
  kmw/engine/18.0.4/kmwuitoolbar.js
  kmw/engine/18.0.4/kmwuitoolbar.js.map
  kmw/engine/18.0.4/osk/ajax-loader.gif
  kmw/engine/18.0.4/osk/globe-hint.css
  kmw/engine/18.0.4/osk/keymanweb-osk.ttf
  kmw/engine/18.0.4/osk/kmwosk.css
  kmw/engine/18.0.4/ui/button/kbdicon.gif
  kmw/engine/18.0.4/ui/button/kmw_button.gif
  kmw/engine/18.0.4/ui/float/kbdicon.gif
  kmw/engine/18.0.4/ui/float/kmicon.gif
  kmw/engine/18.0.4/ui/ios/kbdicon.png
  kmw/engine/18.0.4/ui/toggle/kbdicon.gif
  kmw/engine/18.0.4/ui/toggle/kmw_logo_16.gif
  kmw/engine/18.0.4/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/18.0.4/ui/toggle/kmw_osk_16.gif
  kmw/engine/18.0.4/ui/toggle/kmwcontroller2.gif
  kmw/engine/18.0.4/ui/toggle/kmwcontroller2x.gif
  kmw/engine/18.0.4/ui/toolbar/blank.gif
  kmw/engine/18.0.4/ui/toolbar/kmwuitoolbar.css
  kmw/engine/18.0.4/ui/toolbar/toolbar.gif
  kmw/engine/18.0.4/ui/toolbar/world.png
Labels: auto

#280 auto: Keyboard and font deployment
  keyboard/fv_klahoose/10.0/fv_klahoose-10.0.js
Labels: auto

#281 auto: KeymanWeb release 17.0.276
  kmw/engine/17.0.276/keymanweb.es5.js
  kmw/engine/17.0.276/keymanweb.es5.js.map
  kmw/engine/17.0.276/keymanweb.js
  kmw/engine/17.0.276/keymanweb.js.map
  kmw/engine/17.0.276/kmwuibutton.js
  kmw/engine/17.0.276/kmwuibutton.js.map
  kmw/engine/17.0.276/kmwuifloat.js
  kmw/engine/17.0.276/kmwuifloat.js.map
  kmw/engine/17.0.276/kmwuitoggle.js
  kmw/engine/17.0.276/kmwuitoggle.js.map
  kmw/engine/17.0.276/kmwuitoolbar.js
  kmw/engine/17.0.276/kmwuitoolbar.js.map
  kmw/engine/17.0.276/osk/ajax-loader.gif
  kmw/engine/17.0.276/osk/globe-hint.css
  kmw/engine/17.0.276/osk/keymanweb-osk.ttf
  kmw/engine/17.0.276/osk/kmwosk.css
  kmw/engine/17.0.276/ui/button/kbdicon.gif
  kmw/engine/17.0.276/ui/button/kmw_button.gif
  kmw/engine/17.0.276/ui/float/kbdicon.gif
  kmw/engine/17.0.276/ui/float/kmicon.gif
  kmw/engine/17.0.276/ui/ios/kbdicon.png
  kmw/engine/17.0.276/ui/toggle/kbdicon.gif
  kmw/engine/17.0.276/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.276/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.276/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.276/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.276/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.276/ui/toolbar/blank.gif
  kmw/engine/17.0.276/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.276/ui/toolbar/toolbar.gif
  kmw/engine/17.0.276/ui/toolbar/world.png
Labels: auto

#282 auto: KeymanWeb release 17.0.276
  kmw/engine/18.0.5/keymanweb.es5.js
  kmw/engine/18.0.5/keymanweb.es5.js.map
  kmw/engine/18.0.5/keymanweb.js
  kmw/engine/18.0.5/keymanweb.js.map
  kmw/engine/18.0.5/kmwuibutton.js
  kmw/engine/18.0.5/kmwuibutton.js.map
  kmw/engine/18.0.5/kmwuifloat.js
  kmw/engine/18.0.5/kmwuifloat.js.map
  kmw/engine/18.0.5/kmwuitoggle.js
  kmw/engine/18.0.5/kmwuitoggle.js.map
  kmw/engine/18.0.5/kmwuitoolbar.js
  kmw/engine/18.0.5/kmwuitoolbar.js.map
  kmw/engine/18.0.5/osk/ajax-loader.gif
  kmw/engine/18.0.5/osk/globe-hint.css
  kmw/engine/18.0.5/osk/keymanweb-osk.ttf
  kmw/engine/18.0.5/osk/kmwosk.css
  kmw/engine/18.0.5/ui/button/kbdicon.gif
  kmw/engine/18.0.5/ui/button/kmw_button.gif
  kmw/engine/18.0.5/ui/float/kbdicon.gif
  kmw/engine/18.0.5/ui/float/kmicon.gif
  kmw/engine/18.0.5/ui/ios/kbdicon.png
  kmw/engine/18.0.5/ui/toggle/kbdicon.gif
  kmw/engine/18.0.5/ui/toggle/kmw_logo_16.gif
  kmw/engine/18.0.5/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/18.0.5/ui/toggle/kmw_osk_16.gif
  kmw/engine/18.0.5/ui/toggle/kmwcontroller2.gif
  kmw/engine/18.0.5/ui/toggle/kmwcontroller2x.gif
  kmw/engine/18.0.5/ui/toolbar/blank.gif
  kmw/engine/18.0.5/ui/toolbar/kmwuitoolbar.css
  kmw/engine/18.0.5/ui/toolbar/toolbar.gif
  kmw/engine/18.0.5/ui/toolbar/world.png
Labels: auto

#283 auto: KeymanWeb release 17.0.277
  kmw/engine/17.0.277/keymanweb.es5.js
  kmw/engine/17.0.277/keymanweb.es5.js.map
  kmw/engine/17.0.277/keymanweb.js
  kmw/engine/17.0.277/keymanweb.js.map
  kmw/engine/17.0.277/kmwuibutton.js
  kmw/engine/17.0.277/kmwuibutton.js.map
  kmw/engine/17.0.277/kmwuifloat.js
  kmw/engine/17.0.277/kmwuifloat.js.map
  kmw/engine/17.0.277/kmwuitoggle.js
  kmw/engine/17.0.277/kmwuitoggle.js.map
  kmw/engine/17.0.277/kmwuitoolbar.js
  kmw/engine/17.0.277/kmwuitoolbar.js.map
  kmw/engine/17.0.277/osk/ajax-loader.gif
  kmw/engine/17.0.277/osk/globe-hint.css
  kmw/engine/17.0.277/osk/keymanweb-osk.ttf
  kmw/engine/17.0.277/osk/kmwosk.css
  kmw/engine/17.0.277/ui/button/kbdicon.gif
  kmw/engine/17.0.277/ui/button/kmw_button.gif
  kmw/engine/17.0.277/ui/float/kbdicon.gif
  kmw/engine/17.0.277/ui/float/kmicon.gif
  kmw/engine/17.0.277/ui/ios/kbdicon.png
  kmw/engine/17.0.277/ui/toggle/kbdicon.gif
  kmw/engine/17.0.277/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.277/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.277/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.277/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.277/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.277/ui/toolbar/blank.gif
  kmw/engine/17.0.277/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.277/ui/toolbar/toolbar.gif
  kmw/engine/17.0.277/ui/toolbar/world.png
Labels: auto

#284 auto: KeymanWeb release 17.0.277
  kmw/engine/18.0.6/keymanweb.es5.js
  kmw/engine/18.0.6/keymanweb.es5.js.map
  kmw/engine/18.0.6/keymanweb.js
  kmw/engine/18.0.6/keymanweb.js.map
  kmw/engine/18.0.6/kmwuibutton.js
  kmw/engine/18.0.6/kmwuibutton.js.map
  kmw/engine/18.0.6/kmwuifloat.js
  kmw/engine/18.0.6/kmwuifloat.js.map
  kmw/engine/18.0.6/kmwuitoggle.js
  kmw/engine/18.0.6/kmwuitoggle.js.map
  kmw/engine/18.0.6/kmwuitoolbar.js
  kmw/engine/18.0.6/kmwuitoolbar.js.map
  kmw/engine/18.0.6/osk/ajax-loader.gif
  kmw/engine/18.0.6/osk/globe-hint.css
  kmw/engine/18.0.6/osk/keymanweb-osk.ttf
  kmw/engine/18.0.6/osk/kmwosk.css
  kmw/engine/18.0.6/ui/button/kbdicon.gif
  kmw/engine/18.0.6/ui/button/kmw_button.gif
  kmw/engine/18.0.6/ui/float/kbdicon.gif
  kmw/engine/18.0.6/ui/float/kmicon.gif
  kmw/engine/18.0.6/ui/ios/kbdicon.png
  kmw/engine/18.0.6/ui/toggle/kbdicon.gif
  kmw/engine/18.0.6/ui/toggle/kmw_logo_16.gif
  kmw/engine/18.0.6/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/18.0.6/ui/toggle/kmw_osk_16.gif
  kmw/engine/18.0.6/ui/toggle/kmwcontroller2.gif
  kmw/engine/18.0.6/ui/toggle/kmwcontroller2x.gif
  kmw/engine/18.0.6/ui/toolbar/blank.gif
  kmw/engine/18.0.6/ui/toolbar/kmwuitoolbar.css
  kmw/engine/18.0.6/ui/toolbar/toolbar.gif
  kmw/engine/18.0.6/ui/toolbar/world.png
Labels: auto

#285 auto: Keyboard and font deployment
  keyboard/fv_dakelh/9.1.5/fv_dakelh-9.1.5.js
Labels: auto

#286 auto: Keyboard and font deployment
  keyboard/fv_kashogotine_yati/10.0/fv_kashogotine_yati-10.0.js
Labels: auto

#287 auto: Keyboard and font deployment
  keyboard/knyaw/1.0/knyaw-1.0.js
Labels: auto

#288 auto: KeymanWeb release 17.0.278
  kmw/engine/17.0.278/keymanweb.es5.js
  kmw/engine/17.0.278/keymanweb.es5.js.map
  kmw/engine/17.0.278/keymanweb.js
  kmw/engine/17.0.278/keymanweb.js.map
  kmw/engine/17.0.278/kmwuibutton.js
  kmw/engine/17.0.278/kmwuibutton.js.map
  kmw/engine/17.0.278/kmwuifloat.js
  kmw/engine/17.0.278/kmwuifloat.js.map
  kmw/engine/17.0.278/kmwuitoggle.js
  kmw/engine/17.0.278/kmwuitoggle.js.map
  kmw/engine/17.0.278/kmwuitoolbar.js
  kmw/engine/17.0.278/kmwuitoolbar.js.map
  kmw/engine/17.0.278/osk/ajax-loader.gif
  kmw/engine/17.0.278/osk/globe-hint.css
  kmw/engine/17.0.278/osk/keymanweb-osk.ttf
  kmw/engine/17.0.278/osk/kmwosk.css
  kmw/engine/17.0.278/ui/button/kbdicon.gif
  kmw/engine/17.0.278/ui/button/kmw_button.gif
  kmw/engine/17.0.278/ui/float/kbdicon.gif
  kmw/engine/17.0.278/ui/float/kmicon.gif
  kmw/engine/17.0.278/ui/ios/kbdicon.png
  kmw/engine/17.0.278/ui/toggle/kbdicon.gif
  kmw/engine/17.0.278/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.278/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.278/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.278/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.278/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.278/ui/toolbar/blank.gif
  kmw/engine/17.0.278/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.278/ui/toolbar/toolbar.gif
  kmw/engine/17.0.278/ui/toolbar/world.png
Labels: auto

#289 auto: Keyboard and font deployment
  keyboard/knyaw/1.0.1/knyaw-1.0.1.js
Labels: auto

#290 auto: Keyboard and font deployment
  keyboard/hcesar/1.2/hcesar-1.2.js
Labels: auto

#291 auto: KeymanWeb release 18.0.7
  kmw/engine/18.0.7/keymanweb.es5.js
  kmw/engine/18.0.7/keymanweb.es5.js.map
  kmw/engine/18.0.7/keymanweb.js
  kmw/engine/18.0.7/keymanweb.js.map
  kmw/engine/18.0.7/kmwuibutton.js
  kmw/engine/18.0.7/kmwuibutton.js.map
  kmw/engine/18.0.7/kmwuifloat.js
  kmw/engine/18.0.7/kmwuifloat.js.map
  kmw/engine/18.0.7/kmwuitoggle.js
  kmw/engine/18.0.7/kmwuitoggle.js.map
  kmw/engine/18.0.7/kmwuitoolbar.js
  kmw/engine/18.0.7/kmwuitoolbar.js.map
  kmw/engine/18.0.7/osk/ajax-loader.gif
  kmw/engine/18.0.7/osk/globe-hint.css
  kmw/engine/18.0.7/osk/keymanweb-osk.ttf
  kmw/engine/18.0.7/osk/kmwosk.css
  kmw/engine/18.0.7/ui/button/kbdicon.gif
  kmw/engine/18.0.7/ui/button/kmw_button.gif
  kmw/engine/18.0.7/ui/float/kbdicon.gif
  kmw/engine/18.0.7/ui/float/kmicon.gif
  kmw/engine/18.0.7/ui/ios/kbdicon.png
  kmw/engine/18.0.7/ui/toggle/kbdicon.gif
  kmw/engine/18.0.7/ui/toggle/kmw_logo_16.gif
  kmw/engine/18.0.7/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/18.0.7/ui/toggle/kmw_osk_16.gif
  kmw/engine/18.0.7/ui/toggle/kmwcontroller2.gif
  kmw/engine/18.0.7/ui/toggle/kmwcontroller2x.gif
  kmw/engine/18.0.7/ui/toolbar/blank.gif
  kmw/engine/18.0.7/ui/toolbar/kmwuitoolbar.css
  kmw/engine/18.0.7/ui/toolbar/toolbar.gif
  kmw/engine/18.0.7/ui/toolbar/world.png
Labels: auto

#292 auto: KeymanWeb release 18.0.7
  kmw/engine/17.0.279/keymanweb.es5.js
  kmw/engine/17.0.279/keymanweb.es5.js.map
  kmw/engine/17.0.279/keymanweb.js
  kmw/engine/17.0.279/keymanweb.js.map
  kmw/engine/17.0.279/kmwuibutton.js
  kmw/engine/17.0.279/kmwuibutton.js.map
  kmw/engine/17.0.279/kmwuifloat.js
  kmw/engine/17.0.279/kmwuifloat.js.map
  kmw/engine/17.0.279/kmwuitoggle.js
  kmw/engine/17.0.279/kmwuitoggle.js.map
  kmw/engine/17.0.279/kmwuitoolbar.js
  kmw/engine/17.0.279/kmwuitoolbar.js.map
  kmw/engine/17.0.279/osk/ajax-loader.gif
  kmw/engine/17.0.279/osk/globe-hint.css
  kmw/engine/17.0.279/osk/keymanweb-osk.ttf
  kmw/engine/17.0.279/osk/kmwosk.css
  kmw/engine/17.0.279/ui/button/kbdicon.gif
  kmw/engine/17.0.279/ui/button/kmw_button.gif
  kmw/engine/17.0.279/ui/float/kbdicon.gif
  kmw/engine/17.0.279/ui/float/kmicon.gif
  kmw/engine/17.0.279/ui/ios/kbdicon.png
  kmw/engine/17.0.279/ui/toggle/kbdicon.gif
  kmw/engine/17.0.279/ui/toggle/kmw_logo_16.gif
  kmw/engine/17.0.279/ui/toggle/kmw_logo_16_down.gif
  kmw/engine/17.0.279/ui/toggle/kmw_osk_16.gif
  kmw/engine/17.0.279/ui/toggle/kmwcontroller2.gif
  kmw/engine/17.0.279/ui/toggle/kmwcontroller2x.gif
  kmw/engine/17.0.279/ui/toolbar/blank.gif
  kmw/engine/17.0.279/ui/toolbar/kmwuitoolbar.css
  kmw/engine/17.0.279/ui/toolbar/toolbar.gif
  kmw/engine/17.0.279/ui/toolbar/world.png
Labels: auto
